export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL';
export const ORDER_UPDATE_STATUS_RESET = 'ORDER_UPDATE_STATUS_RESET';

export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';
export const ORDER_CANCEL_RESET = 'ORDER_CANCEL_RESET';

export const ORDER_PREVIEW_REQUEST = 'ORDER_PREVIEW_REQUEST';
export const ORDER_PREVIEW_SUCCESS = 'ORDER_PREVIEW_SUCCESS';
export const ORDER_PREVIEW_FAIL = 'ORDER_PREVIEW_FAIL';

export const BILL_OF_LANDING_REQUEST = 'BILL_OF_LANDING_REQUEST';
export const BILL_OF_LANDING_SUCCESS = 'BILL_OF_LANDING_SUCCESS';
export const BILL_OF_LANDING_FAIL = 'BILL_OF_LANDING_FAIL';

export const UPDATE_COD_REQUEST = 'UPDATE_COD_REQUEST';
export const UPDATE_COD_SUCCESS = 'UPDATE_COD_SUCCESS';
export const UPDATE_COD_FAIL = 'UPDATE_COD_FAIL';
