export const VOUCHER_REQUEST = 'VOUCHER_REQUEST';
export const VOUCHER_SUCCESS = 'VOUCHER_SUCCESS';
export const VOUCHER_FAIL = 'VOUCHER_FAIL';
export const UPDATE_WHEN_DELETE_VOUCHER_SUCCESS = 'UPDATE_WHEN_DELETE_VOUCHER_SUCCESS';
export const UPDATE_WHEN_ADD_VOUCHER_SUCCESS = 'UPDATE_WHEN_ADD_VOUCHER_SUCCESS';

export const VOUCHER_ADD_REQUEST = 'VOUCHER_ADD_REQUEST';
export const VOUCHER_ADD_SUCCESS = 'VOUCHER_ADD_SUCCESS';
export const VOUCHER_ADD_FAIL = 'VOUCHER_ADD_FAIL';
export const VOUCHER_ADD_RESET = 'VOUCHER_ADD_RESET';

export const VOUCHER_UPDATE_REQUEST = 'VOUCHER_UPDATE_REQUEST';
export const VOUCHER_UPDATE_SUCCESS = 'VOUCHER_UPDATE_SUCCESS';
export const VOUCHER_UPDATE_FAIL = 'VOUCHER_UPDATE_FAIL';
export const VOUCHER_UPDATE_RESET = 'VOUCHER_UPDATE_RESET';

export const VOUCHER_DELETE_REQUEST = 'VOUCHER_DELETE_REQUEST';
export const VOUCHER_DELETE_SUCCESS = 'VOUCHER_DELETE_SUCCESS';
export const VOUCHER_DELETE_FAIL = 'VOUCHER_DELETE_FAIL';
export const VOUCHER_DELETE_RESET = 'VOUCHER_DELETE_RESET';
