const ADDRESS_REQUEST = 'ADDRESS_REQUEST';
const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS';
const ADDRESS_FAIL = 'ADDRESS_FAIL';

const SHIPPING_FEE_REQUEST = 'SHIPPING_FEE_REQUEST';
const SHIPPING_FEE_SUCCESS = 'SHIPPING_FEE_SUCCESS';
const SHIPPING_FEE_FAIL = 'ADDRESS_FAIL';
export {
    ADDRESS_FAIL,
    ADDRESS_REQUEST,
    ADDRESS_SUCCESS,
    SHIPPING_FEE_REQUEST,
    SHIPPING_FEE_SUCCESS,
    SHIPPING_FEE_FAIL,
};
