const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
const CART_LIST_FAIL = 'CART_LIST_FAIL';

const CART_CREATE_REQUEST = 'CART_CREATE_REQUEST';
const CART_CREATE_SUCCESS = 'CART_CREATE_SUCCESS';
const CART_CREATE_FAIL = 'CART_CREATE_FAIL';

const CART_ADD_ITEM = 'CART_ADD_ITEM';
const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';
const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
const CART_LIST_MY_RESET = 'CART_LIST_MY_RESET';

const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
const CART_DELETE_FAIL = 'CART_DELETE_FAIL';

const CART_CLEAR_SUCCESS = 'CART_CLEAR_SUCCESS';

const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';
const CART_UPDATE_RESET = 'CART_UPDATE_RESET';

const CART_ADD_PRODUCT_ORDER_REQUEST = 'CART_ADD_PRODUCT_ORDER_REQUEST';
const CART_ADD_PRODUCT_ORDER_SUCCESS = 'CART_ADD_PRODUCT_ORDER_SUCCESS';
const CART_SAVE_SHIPPING_ADDRESS_ORDER = 'CART_SAVE_SHIPPING_ADDRESS_ORDER';
const CART_ADD_PRODUCT_ORDER_FAIL = 'CART_ADD_PRODUCT_ORDER_FAIL';
const CART_ORDER_SHIPPING_ADDRESS = 'CART_ORDER_SHIPPING_ADDRESS';
const CART_ORDER_RESET = 'CART_ORDER_RESET';

export default {
    CART_LIST_REQUEST,
    CART_LIST_SUCCESS,
    CART_LIST_FAIL,
    CART_CREATE_REQUEST,
    CART_CREATE_SUCCESS,
    CART_CREATE_FAIL,
    CART_ADD_ITEM,
    CART_REMOVE_ITEM,
    CART_CLEAR_ITEMS,
    CART_SAVE_SHIPPING_ADDRESS,
    CART_SAVE_PAYMENT_METHOD,
    CART_LIST_MY_RESET,
    CART_DELETE_REQUEST,
    CART_DELETE_SUCCESS,
    CART_DELETE_FAIL,
    CART_CLEAR_SUCCESS,
    CART_UPDATE_REQUEST,
    CART_UPDATE_SUCCESS,
    CART_UPDATE_FAIL,
    CART_UPDATE_RESET,
    CART_ADD_PRODUCT_ORDER_REQUEST,
    CART_ADD_PRODUCT_ORDER_SUCCESS,
    CART_SAVE_SHIPPING_ADDRESS_ORDER,
    CART_ADD_PRODUCT_ORDER_FAIL,
    CART_ORDER_SHIPPING_ADDRESS,
    CART_ORDER_RESET,
};
