export const ADDRESS_DISTRICT_LIST_REQUEST = 'ADDRESS_DISTRICT_LIST_REQUEST';
export const ADDRESS_DISTRICT_LIST_SUCCESS = 'ADDRESS_DISTRICT_LIST_SUCCESS';
export const ADDRESS_DISTRICT_LIST_FAIL = 'ADDRESS_DISTRICT_LIST_FAIL';

export const ADDRESS_WARD_LIST_REQUEST = 'ADDRESS_WARD_LIST_REQUEST';
export const ADDRESS_WARD_LIST_SUCCESS = 'ADDRESS_WARD_LIST_SUCCESS';
export const ADDRESS_WARD_LIST_FAIL = 'ADDRESS_WARD_LIST_FAIL';

export const ADDRESS_PROVINCE_LIST_REQUEST = 'ADDRESS_PROVINCE_LIST_REQUEST';
export const ADDRESS_PROVINCE_LIST_SUCCESS = 'ADDRESS_PROVINCE_LIST_SUCCESS';
export const ADDRESS_PROVINCE_LIST_FAIL = 'ADDRESS_PROVINCE_LIST_FAIL';

export const SHIPPING_FEE_REQUEST = 'SHIPPING_FEE_REQUEST';
export const SHIPPING_FEE_SUCCESS = 'SHIPPING_FEE_SUCCESS';
export const SHIPPING_FEE_FAIL = 'ADDRESS_FAIL';
