export const MY_VOUCHER_REQUEST = 'MY_VOUCHER_REQUEST';
export const MY_VOUCHER_SUCCESS = 'MY_VOUCHER_SUCCESS';
export const MY_VOUCHER_FAIL = 'MY_VOUCHER_FAIL';

export const PUBLIC_VOUCHER_REQUEST = 'PUBLIC_VOUCHER_REQUEST';
export const PUBLIC_VOUCHER_SUCCESS = 'PUBLIC_VOUCHER_SUCCESS';
export const PUBLIC_VOUCHER_FAIL = 'PUBLIC_VOUCHER_FAIL';

export const ADD_VOUCHER_REQUEST = 'ADD_VOUCHER_REQUEST';
export const ADD_VOUCHER_SUCCESS = 'ADD_VOUCHER_SUCCESS';
export const ADD_VOUCHER_FAIL = 'ADD_VOUCHER_FAIL';
